public class VariableDemoClass {
    Public String email ='test@test.com';
    Public Decimal englishMarks = 24.50;
    Public Date doj = System.today();
    public VariableDemoClass(){
        system.debug('email....'+email);
        system.debug('englishMarks....'+englishMarks);
        system.debug('doj....'+doj);
    }
     public VariableDemoClass(String email , Date doj){
         
     }
    public static void addition(Integer a, Integer b){
        
    }
    public static void addition(Integer a, Integer b, Integer c){
        
    }
    
}